// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import java.util.Scanner;

import com.sun.corba.se.spi.resolver.Resolver;

import Ahorcado.Horca;
import Ahorcado.Palabra;
import java.lang.Character;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public static Horca horca;
	/**
	 * 
	 */
	public static Palabra palabra;

	/**
	 * Muestra el estado de la horca y los resultados de palabra
	 */
	public static void mostrarProgreso() {
		horca.dibujar();
		palabra.mostrarResultados();
	}

	/**
	 * Solicita una letra al usuario
	 * @return letra Devuelve la letra pasandola a minúscula
	 */
	public static char pedirLetra() {
		Scanner entrada = new Scanner (System.in);
		
		System.out.print("Introduzca una letra: ");
		char letra = entrada.next().charAt(0);
		
		
		return Character.toLowerCase(letra);
		
	}

	/**
	 * Pide la respuesta al jugador.
	 * 
	 * @return palabra true si el jugado ha acertado o  false en caso contrario.
	 */
	public static boolean resolver() {
		Scanner entrada = new Scanner (System.in);
		
		System.out.print("Introduzca la respuesta: ");
		 return palabra.comprobarPalabra(entrada.nextLine());
	}

	/**
	 * Comprueba tanto si hemos agotado los fallos como si hemos acertado todas las letras.
	 * @return fin true si hemos ganado o perdido, false si todavía jugamos.
	 */
	public static boolean comprobarFinal() {
		return horca.comprobarSiPerdido() || palabra.comprobarSiGanado();
	}
	/**
	 * Te permite elegir varias opciones del panel
	 * 
	 * @return devuelve el número que has elegido y ejecuta dicho código
	 */
	public static int elegirDelMenu(){
		Scanner entrada = new Scanner (System.in);

		System.out.println("Elige una opción: ");
		System.out.println("1. Letra");
		System.out.println("2. Resolver");
		System.out.println("3. Abandonar");

		return entrada.nextInt();
	}
	
	public static void main(String[] args) {
		horca = new Horca();
		palabra = new Palabra();
		boolean noHaResueltoMal = true;
		palabra.elegirPalabra();
		
		while(!comprobarFinal() && noHaResueltoMal){
			
			switch (elegirDelMenu()) {
			case 1:
				palabra.comprobarLetra(pedirLetra());
				horca.incrementarFallo();
				mostrarProgreso();
			break;
			case 2: 
				if(resolver()) 
					System.out.println("Has ganado!");
				else 
					System.out.println("Lo siento, has perdido. :(");
					noHaResueltoMal = false;
			break;
			case 3:
				System.exit(0);
				default:
				break;
			}
		}
		pedirLetra();

	}
};
